cache:
  key: ${CI_PROJECT_ID}
  paths:
  - node_modules/
  - dist/

build:
  image: node:latest
  script:
  - [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - export TAG=${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}-$(date "+%Y%m%d%H%M")
  - eval $(ssh-agent -s)
  - ssh-add - <<< $(curl https://${KEYSTORE_SERVER}/gitlab-sshkey/id_ecdsa -u gitlab:${key_store_passwd})
  - git push --set-upstream git@github.com:telegram-sms/user-guide.git HEAD:refs/heads/${CI_COMMIT_REF_NAME}
  - npm install -g gitbook-cli
  - git clone git@github.com:telegram-sms/guide.telegram-sms.com.git _book
  - rm ./_book/*
  - gitbook build
  - cd _book
  - git add .
  - git commit -m $TAG
  - git push --set-upstream git@github.com:telegram-sms/guide.telegram-sms.com.git HEAD:refs/heads/${CI_COMMIT_REF_NAME}